import type { Product } from './tipos';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Monitor',
    category: 'Electronics',
    sku: 'SKU-001',
    stock: 25,
    price: 199.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/100/400/300',
    imageHint: 'computer monitor',
    historicalSales: [
      { month: 'Jan', sales: 50 },
      { month: 'Feb', sales: 60 },
      { month: 'Mar', sales: 70 },
      { month: 'Apr', sales: 55 },
      { month: 'May', sales: 80 },
      { month: 'Jun', sales: 90 },
    ],
  },
  {
    id: '2',
    name: 'Ergonomic Keyboard',
    category: 'Peripherals',
    sku: 'SKU-002',
    stock: 8,
    price: 129.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/101/400/300',
    imageHint: 'ergonomic keyboard',
    historicalSales: [
      { month: 'Jan', sales: 80 },
      { month: 'Feb', sales: 95 },
      { month: 'Mar', sales: 110 },
      { month: 'Apr', sales: 90 },
      { month: 'May', sales: 120 },
      { month: 'Jun', sales: 130 },
    ],
  },
  {
    id: '3',
    name: 'Wireless Mouse',
    category: 'Peripherals',
    sku: 'SKU-003',
    stock: 40,
    price: 49.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/102/400/300',
    imageHint: 'wireless mouse',
    historicalSales: [
      { month: 'Jan', sales: 200 },
      { month: 'Feb', sales: 220 },
      { month: 'Mar', sales: 250 },
      { month: 'Apr', sales: 210 },
      { month: 'May', sales: 280 },
      { month: 'Jun', sales: 300 },
    ],
  },
  {
    id: '4',
    name: 'USB-C Hub',
    category: 'Accessories',
    sku: 'SKU-004',
    stock: 5,
    price: 59.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/103/400/300',
    imageHint: 'usb hub',
    historicalSales: [
      { month: 'Jan', sales: 150 },
      { month: 'Feb', sales: 160 },
      { month: 'Mar', sales: 180 },
      { month: 'Apr', sales: 140 },
      { month: 'May', sales: 200 },
      { month: 'Jun', sales: 210 },
    ],
  },
  {
    id: '5',
    name: 'Noise-Cancelling Headphones',
    category: 'Audio',
    sku: 'SKU-005',
    stock: 15,
    price: 249.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/104/400/300',
    imageHint: 'headphones',
    historicalSales: [
      { month: 'Jan', sales: 70 },
      { month: 'Feb', sales: 85 },
      { month: 'Mar', sales: 95 },
      { month: 'Apr', sales: 80 },
      { month: 'May', sales: 110 },
      { month: 'Jun', sales: 120 },
    ],
  },
  {
    id: '6',
    name: '4K Webcam',
    category: 'Electronics',
    sku: 'SKU-006',
    stock: 20,
    price: 159.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/105/400/300',
    imageHint: 'webcam',
    historicalSales: [
      { month: 'Jan', sales: 60 },
      { month: 'Feb', sales: 70 },
      { month: 'Mar', sales: 80 },
      { month: 'Apr', sales: 65 },
      { month: 'May', sales: 90 },
      { month: 'Jun', sales: 100 },
    ],
  },
  {
    id: '7',
    name: 'Adjustable Standing Desk',
    category: 'Furniture',
    sku: 'SKU-007',
    stock: 12,
    price: 499.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/106/400/300',
    imageHint: 'standing desk',
    historicalSales: [
      { month: 'Jan', sales: 30 },
      { month: 'Feb', sales: 35 },
      { month: 'Mar', sales: 40 },
      { month: 'Apr', sales: 32 },
      { month: 'May', sales: 45 },
      { month: 'Jun', sales: 50 },
    ],
  },
  {
    id: '8',
    name: 'LED Desk Lamp',
    category: 'Furniture',
    sku: 'SKU-008',
    stock: 30,
    price: 39.99,
    status: 'disabled',
    imageUrl: 'https://picsum.photos/seed/107/400/300',
    imageHint: 'desk lamp',
    historicalSales: [
      { month: 'Jan', sales: 100 },
      { month: 'Feb', sales: 110 },
      { month: 'Mar', sales: 120 },
      { month: 'Apr', sales: 95 },
      { month: 'May', sales: 130 },
      { month: 'Jun', sales: 140 },
    ],
  },
  {
    id: '9',
    name: 'Laptop Stand',
    category: 'Accessories',
    sku: 'SKU-009',
    stock: 50,
    price: 29.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/108/400/300',
    imageHint: 'laptop stand',
    historicalSales: [
      { month: 'Jan', sales: 180 },
      { month: 'Feb', sales: 200 },
      { month: 'Mar', sales: 220 },
      { month: 'Apr', sales: 190 },
      { month: 'May', sales: 240 },
      { month: 'Jun', sales: 260 },
    ],
  },
  {
    id: '10',
    name: '1TB External SSD',
    category: 'Storage',
    sku: 'SKU-010',
    stock: 22,
    price: 89.99,
    status: 'active',
    imageUrl: 'https://picsum.photos/seed/109/400/300',
    imageHint: 'external drive',
    historicalSales: [
      { month: 'Jan', sales: 90 },
      { month: 'Feb', sales: 105 },
      { month: 'Mar', sales: 115 },
      { month: 'Apr', sales: 95 },
      { month: 'May', sales: 130 },
      { month: 'Jun', sales: 140 },
    ],
  },
];
